### ISSUE TITLE
HTTP 413 Status Code on saving Transcript markup

### ISSUE THREAD

**Issue by maboa** [hyperaudio/ha-api#10]
In the converter with a large amount of markup you get (for example) : 

POST http://newsarchive.api.hyperaud.io/v1/maboamaboa/transcripts 413 (Request Entity Too Large)
converter.html:1 XMLHttpRequest cannot load http://newsarchive.api.hyperaud.io/v1/maboamaboa/transcripts. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://newsarchive.hyperaud.io' is therefore not allowed access. The response had HTTP status code 413.

**Comment by Laurian** [comment]
max JSON set to 50mb
